// Catálogo de Sets Rápidos para Item Maker y Warehouse
export interface QuickSetPiece {
  group: number;
  index: number;
  name: string;
}

export interface QuickSetDef {
  id: string;
  name: string;
  cat: 'DW' | 'DK' | 'FE' | 'MG' | 'DL' | 'ACC';
  catLabel: string;
  defaultAncient: number;
  pieces: QuickSetPiece[];
}

export { MakerCategoryDef, MAKER_CATEGORIES } from './makerCategories';

export const QUICK_SETS_CATALOG: QuickSetDef[] = [
  // --- MAGO (DW / SM / GM) ---
  {
    id: 'hades',
    name: 'Hades Set',
    cat: 'DW',
    catLabel: 'Mago',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 52, name: 'Hades Helm' },
      { group: 8, index: 52, name: 'Hades Armor' },
      { group: 9, index: 52, name: 'Hades Pants' },
      { group: 10, index: 52, name: 'Hades Gloves' },
      { group: 11, index: 52, name: 'Hades Boots' },
    ],
  },
  {
    id: 'dark_soul',
    name: 'Dark Soul Set',
    cat: 'DW',
    catLabel: 'Mago',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 22, name: 'Dark Soul Helm' },
      { group: 8, index: 22, name: 'Dark Soul Armor' },
      { group: 9, index: 22, name: 'Dark Soul Pants' },
      { group: 10, index: 22, name: 'Dark Soul Gloves' },
      { group: 11, index: 22, name: 'Dark Soul Boots' },
    ],
  },
  {
    id: 'grand_soul',
    name: 'Grand Soul Set',
    cat: 'DW',
    catLabel: 'Mago',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 18, name: 'Grand Soul Helm' },
      { group: 8, index: 18, name: 'Grand Soul Armor' },
      { group: 9, index: 18, name: 'Grand Soul Pants' },
      { group: 10, index: 18, name: 'Grand Soul Gloves' },
      { group: 11, index: 18, name: 'Grand Soul Boots' },
    ],
  },
  {
    id: 'legendary',
    name: 'Legendary Set',
    cat: 'DW',
    catLabel: 'Mago',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 3, name: 'Legendary Helm' },
      { group: 8, index: 3, name: 'Legendary Armor' },
      { group: 9, index: 3, name: 'Legendary Pants' },
      { group: 10, index: 3, name: 'Legendary Gloves' },
      { group: 11, index: 3, name: 'Legendary Boots' },
    ],
  },
  {
    id: 'bone',
    name: 'Bone Set',
    cat: 'DW',
    catLabel: 'Mago',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 4, name: 'Bone Helm' },
      { group: 8, index: 4, name: 'Bone Armor' },
      { group: 9, index: 4, name: 'Bone Pants' },
      { group: 10, index: 4, name: 'Bone Gloves' },
      { group: 11, index: 4, name: 'Bone Boots' },
    ],
  },
  {
    id: 'pad',
    name: 'Pad Set',
    cat: 'DW',
    catLabel: 'Mago',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 2, name: 'Pad Helm' },
      { group: 8, index: 2, name: 'Pad Armor' },
      { group: 9, index: 2, name: 'Pad Pants' },
      { group: 10, index: 2, name: 'Pad Gloves' },
      { group: 11, index: 2, name: 'Pad Boots' },
    ],
  },
  {
    id: 'sphinx',
    name: 'Sphinx Set',
    cat: 'DW',
    catLabel: 'Mago',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 7, name: 'Sphinx Helm' },
      { group: 8, index: 7, name: 'Sphinx Armor' },
      { group: 9, index: 7, name: 'Sphinx Pants' },
      { group: 10, index: 7, name: 'Sphinx Gloves' },
      { group: 11, index: 7, name: 'Sphinx Boots' },
    ],
  },
  {
    id: 'venom',
    name: 'Venom Mist Set',
    cat: 'DW',
    catLabel: 'Mago',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 30, name: 'Venom Mist Helm' },
      { group: 8, index: 30, name: 'Venom Mist Armor' },
      { group: 9, index: 30, name: 'Venom Mist Pants' },
      { group: 10, index: 30, name: 'Venom Mist Gloves' },
      { group: 11, index: 30, name: 'Venom Mist Boots' },
    ],
  },

  // --- GUERRERO (DK / BK / BM) ---
  {
    id: 'titan',
    name: 'Titan Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 45, name: 'Titan Helm' },
      { group: 8, index: 45, name: 'Titan Armor' },
      { group: 9, index: 45, name: 'Titan Pants' },
      { group: 10, index: 45, name: 'Titan Gloves' },
      { group: 11, index: 45, name: 'Titan Boots' },
    ],
  },
  {
    id: 'brave',
    name: 'Brave Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 46, name: 'Brave Helm' },
      { group: 8, index: 46, name: 'Brave Armor' },
      { group: 9, index: 46, name: 'Brave Pants' },
      { group: 10, index: 46, name: 'Brave Gloves' },
      { group: 11, index: 46, name: 'Brave Boots' },
    ],
  },
  {
    id: 'dragon_knight',
    name: 'Dragon Knight Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 29, name: 'Dragon Knight Helm' },
      { group: 8, index: 29, name: 'Dragon Knight Armor' },
      { group: 9, index: 29, name: 'Dragon Knight Pants' },
      { group: 10, index: 29, name: 'Dragon Knight Gloves' },
      { group: 11, index: 29, name: 'Dragon Knight Boots' },
    ],
  },
  {
    id: 'great_dragon',
    name: 'Great Dragon Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 21, name: 'Great Dragon Helm' },
      { group: 8, index: 21, name: 'Great Dragon Armor' },
      { group: 9, index: 21, name: 'Great Dragon Pants' },
      { group: 10, index: 21, name: 'Great Dragon Gloves' },
      { group: 11, index: 21, name: 'Great Dragon Boots' },
    ],
  },
  {
    id: 'dark_phoenix',
    name: 'Dark Phoenix Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 17, name: 'Dark Phoenix Helm' },
      { group: 8, index: 17, name: 'Dark Phoenix Armor' },
      { group: 9, index: 17, name: 'Dark Phoenix Pants' },
      { group: 10, index: 17, name: 'Dark Phoenix Gloves' },
      { group: 11, index: 17, name: 'Dark Phoenix Boots' },
    ],
  },
  {
    id: 'black_dragon',
    name: 'Black Dragon Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 16, name: 'Black Dragon Helm' },
      { group: 8, index: 16, name: 'Black Dragon Armor' },
      { group: 9, index: 16, name: 'Black Dragon Pants' },
      { group: 10, index: 16, name: 'Black Dragon Gloves' },
      { group: 11, index: 16, name: 'Black Dragon Boots' },
    ],
  },
  {
    id: 'dragon',
    name: 'Dragon Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 1, name: 'Dragon Helm' },
      { group: 8, index: 1, name: 'Dragon Armor' },
      { group: 9, index: 1, name: 'Dragon Pants' },
      { group: 10, index: 1, name: 'Dragon Gloves' },
      { group: 11, index: 1, name: 'Dragon Boots' },
    ],
  },
  {
    id: 'plate',
    name: 'Plate Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 9, name: 'Plate Helm' },
      { group: 8, index: 9, name: 'Plate Armor' },
      { group: 9, index: 9, name: 'Plate Pants' },
      { group: 10, index: 9, name: 'Plate Gloves' },
      { group: 11, index: 9, name: 'Plate Boots' },
    ],
  },
  {
    id: 'scale',
    name: 'Scale Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 6, name: 'Scale Helm' },
      { group: 8, index: 6, name: 'Scale Armor' },
      { group: 9, index: 6, name: 'Scale Pants' },
      { group: 10, index: 6, name: 'Scale Gloves' },
      { group: 11, index: 6, name: 'Scale Boots' },
    ],
  },
  {
    id: 'brass',
    name: 'Brass Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 8, name: 'Brass Helm' },
      { group: 8, index: 8, name: 'Brass Armor' },
      { group: 9, index: 8, name: 'Brass Pants' },
      { group: 10, index: 8, name: 'Brass Gloves' },
      { group: 11, index: 8, name: 'Brass Boots' },
    ],
  },
  {
    id: 'leather',
    name: 'Leather Set',
    cat: 'DK',
    catLabel: 'Guerrero',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 5, name: 'Leather Helm' },
      { group: 8, index: 5, name: 'Leather Armor' },
      { group: 9, index: 5, name: 'Leather Pants' },
      { group: 10, index: 5, name: 'Leather Gloves' },
      { group: 11, index: 5, name: 'Leather Boots' },
    ],
  },

  // --- ELFA (FE / ME / HE) ---
  {
    id: 'seraphim',
    name: 'Seraphim Set',
    cat: 'FE',
    catLabel: 'Elfa',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 49, name: 'Seraphim Helm' },
      { group: 8, index: 49, name: 'Seraphim Armor' },
      { group: 9, index: 49, name: 'Seraphim Pants' },
      { group: 10, index: 49, name: 'Seraphim Gloves' },
      { group: 11, index: 49, name: 'Seraphim Boots' },
    ],
  },
  {
    id: 'sylphid_ray',
    name: 'Sylphid Ray Set',
    cat: 'FE',
    catLabel: 'Elfa',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 31, name: 'Sylphid Ray Helm' },
      { group: 8, index: 31, name: 'Sylphid Ray Armor' },
      { group: 9, index: 31, name: 'Sylphid Ray Pants' },
      { group: 10, index: 31, name: 'Sylphid Ray Gloves' },
      { group: 11, index: 31, name: 'Sylphid Ray Boots' },
    ],
  },
  {
    id: 'red_spirit',
    name: 'Red Spirit Set',
    cat: 'FE',
    catLabel: 'Elfa',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 24, name: 'Red Spirit Helm' },
      { group: 8, index: 24, name: 'Red Spirit Armor' },
      { group: 9, index: 24, name: 'Red Spirit Pants' },
      { group: 10, index: 24, name: 'Red Spirit Gloves' },
      { group: 11, index: 24, name: 'Red Spirit Boots' },
    ],
  },
  {
    id: 'divine',
    name: 'Divine Set',
    cat: 'FE',
    catLabel: 'Elfa',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 19, name: 'Divine Helm' },
      { group: 8, index: 19, name: 'Divine Armor' },
      { group: 9, index: 19, name: 'Divine Pants' },
      { group: 10, index: 19, name: 'Divine Gloves' },
      { group: 11, index: 19, name: 'Divine Boots' },
    ],
  },
  {
    id: 'guardian',
    name: 'Guardian Set',
    cat: 'FE',
    catLabel: 'Elfa',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 14, name: 'Guardian Helm' },
      { group: 8, index: 14, name: 'Guardian Armor' },
      { group: 9, index: 14, name: 'Guardian Pants' },
      { group: 10, index: 14, name: 'Guardian Gloves' },
      { group: 11, index: 14, name: 'Guardian Boots' },
    ],
  },
  {
    id: 'wind',
    name: 'Wind Set',
    cat: 'FE',
    catLabel: 'Elfa',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 12, name: 'Wind Helm' },
      { group: 8, index: 12, name: 'Wind Armor' },
      { group: 9, index: 12, name: 'Wind Pants' },
      { group: 10, index: 12, name: 'Wind Gloves' },
      { group: 11, index: 12, name: 'Wind Boots' },
    ],
  },

  // --- MAGOCABALLERO (MG / DM) ---
  {
    id: 'phantom',
    name: 'Phantom Set',
    cat: 'MG',
    catLabel: 'Magocaballero',
    defaultAncient: 0,
    pieces: [
      { group: 8, index: 47, name: 'Phantom Armor' },
      { group: 9, index: 47, name: 'Phantom Pants' },
      { group: 10, index: 47, name: 'Phantom Gloves' },
      { group: 11, index: 47, name: 'Phantom Boots' },
    ],
  },
  {
    id: 'volcano',
    name: 'Volcano Set',
    cat: 'MG',
    catLabel: 'Magocaballero',
    defaultAncient: 0,
    pieces: [
      { group: 8, index: 32, name: 'Volcano Armor' },
      { group: 9, index: 32, name: 'Volcano Pants' },
      { group: 10, index: 32, name: 'Volcano Gloves' },
      { group: 11, index: 32, name: 'Volcano Boots' },
    ],
  },
  {
    id: 'hurricane',
    name: 'Hurricane Set',
    cat: 'MG',
    catLabel: 'Magocaballero',
    defaultAncient: 0,
    pieces: [
      { group: 8, index: 23, name: 'Hurricane Armor' },
      { group: 9, index: 23, name: 'Hurricane Pants' },
      { group: 10, index: 23, name: 'Hurricane Gloves' },
      { group: 11, index: 23, name: 'Hurricane Boots' },
    ],
  },
  {
    id: 'thunder_hawk',
    name: 'Thunder Hawk Set',
    cat: 'MG',
    catLabel: 'Magocaballero',
    defaultAncient: 0,
    pieces: [
      { group: 8, index: 20, name: 'Thunder Hawk Armor' },
      { group: 9, index: 20, name: 'Thunder Hawk Pants' },
      { group: 10, index: 20, name: 'Thunder Hawk Gloves' },
      { group: 11, index: 20, name: 'Thunder Hawk Boots' },
    ],
  },
  {
    id: 'storm_crow',
    name: 'Storm Crow Set',
    cat: 'MG',
    catLabel: 'Magocaballero',
    defaultAncient: 0,
    pieces: [
      { group: 8, index: 15, name: 'Storm Crow Armor' },
      { group: 9, index: 15, name: 'Storm Crow Pants' },
      { group: 10, index: 15, name: 'Storm Crow Gloves' },
      { group: 11, index: 15, name: 'Storm Crow Boots' },
    ],
  },

  // --- SEÑOR OSCURO (DL / LE) ---
  {
    id: 'royal',
    name: 'Royal Set',
    cat: 'DL',
    catLabel: 'Señor Oscuro',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 51, name: 'Royal Mask' },
      { group: 8, index: 51, name: 'Royal Armor' },
      { group: 9, index: 51, name: 'Royal Pants' },
      { group: 10, index: 51, name: 'Royal Gloves' },
      { group: 11, index: 51, name: 'Royal Boots' },
    ],
  },
  {
    id: 'sunlight',
    name: 'Sunlight Set',
    cat: 'DL',
    catLabel: 'Señor Oscuro',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 33, name: 'Sunlight Mask' },
      { group: 8, index: 33, name: 'Sunlight Armor' },
      { group: 9, index: 33, name: 'Sunlight Pants' },
      { group: 10, index: 33, name: 'Sunlight Gloves' },
      { group: 11, index: 33, name: 'Sunlight Boots' },
    ],
  },
  {
    id: 'dark_master',
    name: 'Dark Master Set',
    cat: 'DL',
    catLabel: 'Señor Oscuro',
    defaultAncient: 0,
    pieces: [
      { group: 7, index: 28, name: 'Dark Master Mask' },
      { group: 8, index: 28, name: 'Dark Master Armor' },
      { group: 9, index: 28, name: 'Dark Master Pants' },
      { group: 10, index: 28, name: 'Dark Master Gloves' },
      { group: 11, index: 28, name: 'Dark Master Boots' },
    ],
  },

  // --- SETS ANCIENT (ACC) ---
  {
    id: 'hyon_dragon',
    name: 'Hyon Dragon (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 5,
    pieces: [
      { group: 7, index: 1, name: 'Hyon Dragon Helm' },
      { group: 8, index: 1, name: 'Hyon Dragon Armor' },
      { group: 11, index: 1, name: 'Hyon Dragon Boots' },
    ],
  },
  {
    id: 'vicious_dragon',
    name: 'Vicious Dragon (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 10,
    pieces: [
      { group: 7, index: 1, name: 'Vicious Dragon Helm' },
      { group: 8, index: 1, name: 'Vicious Dragon Armor' },
      { group: 9, index: 1, name: 'Vicious Dragon Pants' },
    ],
  },
  {
    id: 'anubis_legendary',
    name: 'Anubis Legendary (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 5,
    pieces: [
      { group: 7, index: 3, name: 'Anubis Legendary Helm' },
      { group: 8, index: 3, name: 'Anubis Legendary Armor' },
      { group: 10, index: 3, name: 'Anubis Legendary Gloves' },
    ],
  },
  {
    id: 'enis_legendary',
    name: 'Enis Legendary (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 10,
    pieces: [
      { group: 7, index: 3, name: 'Enis Legendary Helm' },
      { group: 8, index: 3, name: 'Enis Legendary Armor' },
      { group: 9, index: 3, name: 'Enis Legendary Pants' },
      { group: 11, index: 3, name: 'Enis Legendary Boots' },
    ],
  },
  {
    id: 'apollo_pad',
    name: 'Apollo Pad (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 5,
    pieces: [
      { group: 7, index: 2, name: 'Apollo Pad Helm' },
      { group: 8, index: 2, name: 'Apollo Pad Armor' },
      { group: 9, index: 2, name: 'Apollo Pad Pants' },
      { group: 10, index: 2, name: 'Apollo Pad Gloves' },
    ],
  },
  {
    id: 'evis_bone',
    name: 'Evis Bone (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 5,
    pieces: [
      { group: 8, index: 4, name: 'Evis Bone Armor' },
      { group: 9, index: 4, name: 'Evis Bone Pants' },
      { group: 11, index: 4, name: 'Evis Bone Boots' },
    ],
  },
  {
    id: 'gaion_storm',
    name: 'Gaion Storm Crow (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 5,
    pieces: [
      { group: 8, index: 15, name: 'Gaion Storm Crow Armor' },
      { group: 9, index: 15, name: 'Gaion Storm Crow Pants' },
      { group: 11, index: 15, name: 'Gaion Storm Crow Boots' },
    ],
  },
  {
    id: 'agnis_black_dragon',
    name: 'Agnis Black Dragon (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 5,
    pieces: [
      { group: 7, index: 16, name: 'Agnis Black Dragon Helm' },
      { group: 8, index: 16, name: 'Agnis Black Dragon Armor' },
      { group: 9, index: 16, name: 'Agnis Black Dragon Pants' },
    ],
  },
  {
    id: 'broy_red_spirit',
    name: 'Broy Red Spirit (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 5,
    pieces: [
      { group: 7, index: 24, name: 'Broy Red Spirit Helm' },
      { group: 8, index: 24, name: 'Broy Red Spirit Armor' },
      { group: 9, index: 24, name: 'Broy Red Spirit Pants' },
      { group: 11, index: 24, name: 'Broy Red Spirit Boots' },
    ],
  },
  {
    id: 'gywen_guardian',
    name: 'Gywen Guardian (Ancient)',
    cat: 'ACC',
    catLabel: 'Sets Ancient',
    defaultAncient: 5,
    pieces: [
      { group: 8, index: 14, name: 'Gywen Guardian Armor' },
      { group: 10, index: 14, name: 'Gywen Guardian Gloves' },
      { group: 11, index: 14, name: 'Gywen Guardian Boots' },
    ],
  },
];