import { CharacterDetail, CharacterSummary, AccountSummary } from '../../types/character';
import { DashboardMetrics } from '../../types/database';
import { MuItemParser } from '../parser/muItemParser';

// Generate realistic 16-byte items for mock character TestBM (Blade Master)
// Slot 0: Knight Blade +15 +Skill +Luck +Option28 +Exc (Dmg2% + ExcDmg10%)
// Slot 1: Dragon Shield +15 +Skill +Luck +Option28 +Exc (Reflect + DmgDec)
// Slot 2: Dragon Helm +15 +Luck +Option28 +Exc
// Slot 3: Dragon Armor +15 +Luck +Option28 +Exc
// Slot 4: Dragon Pants +15 +Luck +Option28 +Exc
// Slot 5: Dragon Gloves +15 +Luck +Option28 +Exc
// Slot 6: Dragon Boots +15 +Luck +Option28 +Exc
// Slot 7: Wings of Dragon +15 +Luck +Option28
// Slot 8: Horn of Fenrir (Gold/Red)
// Slot 9: Pendant of Lightning +Exc (Speed7 + ExcDmg10%)
// Slot 10: Ring of Ice +Exc (Reflect + DmgDec)
// Slot 11: Ring of Poison +Exc (Reflect + DmgDec)
// Slot 12+: Jewel of Bless, Jewel of Soul, Jewel of Chaos in inventory grid

const mockItems = [
  // Slot 0: Knight Blade (Group 0, Index 20)
  {
    slot: 0,
    hex: '',
    group: 0,
    index: 20,
    id: 20,
    name: 'Knight Blade',
    level: 15,
    skill: true,
    luck: true,
    option: 7, // +28
    durability: 255,
    serial: 12345678,
    excellentFlags: 0x24, // Exc Dmg 10% + Dmg 2%
    ancientOption: 0,
    option380: true,
    harmonyType: 1,
    harmonyLevel: 13,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 1,
    height: 3,
    isExcellent: true,
    isAncient: false,
    category: 'weapon' as const,
    spriteKey: 'sword',
  },
  // Slot 1: Dragon Shield (Group 6, Index 14)
  {
    slot: 1,
    hex: '',
    group: 6,
    index: 14,
    id: 206,
    name: 'Dragon Shield',
    level: 15,
    skill: true,
    luck: true,
    option: 7,
    durability: 255,
    serial: 12345679,
    excellentFlags: 0x0C, // Dmg Dec 4% + Reflect 5%
    ancientOption: 0,
    option380: true,
    harmonyType: 2,
    harmonyLevel: 13,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 2,
    height: 2,
    isExcellent: true,
    isAncient: false,
    category: 'armor' as const,
    spriteKey: 'shield',
  },
  // Slot 2: Dragon Helm (Group 7, Index 1)
  {
    slot: 2,
    hex: '',
    group: 7,
    index: 1,
    id: 225,
    name: 'Dragon Helm',
    level: 15,
    skill: false,
    luck: true,
    option: 7,
    durability: 255,
    serial: 12345680,
    excellentFlags: 0x0C,
    ancientOption: 1, // Vicious
    option380: false,
    harmonyType: 3,
    harmonyLevel: 10,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 2,
    height: 2,
    isExcellent: true,
    isAncient: true,
    category: 'armor' as const,
    spriteKey: 'knight',
  },
  // Slot 3: Dragon Armor (Group 8, Index 1)
  {
    slot: 3,
    hex: '',
    group: 8,
    index: 1,
    id: 257,
    name: 'Dragon Armor',
    level: 15,
    skill: false,
    luck: true,
    option: 7,
    durability: 255,
    serial: 12345681,
    excellentFlags: 0x0C,
    ancientOption: 1, // Vicious
    option380: false,
    harmonyType: 3,
    harmonyLevel: 10,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 2,
    height: 2,
    isExcellent: true,
    isAncient: true,
    category: 'armor' as const,
    spriteKey: 'tshirt-crew',
  },
  // Slot 4: Dragon Pants (Group 9, Index 1)
  {
    slot: 4,
    hex: '',
    group: 9,
    index: 1,
    id: 289,
    name: 'Dragon Pants',
    level: 15,
    skill: false,
    luck: true,
    option: 7,
    durability: 255,
    serial: 12345682,
    excellentFlags: 0x0C,
    ancientOption: 1,
    option380: false,
    harmonyType: 3,
    harmonyLevel: 10,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 2,
    height: 2,
    isExcellent: true,
    isAncient: true,
    category: 'armor' as const,
    spriteKey: 'run-fast',
  },
  // Slot 5: Dragon Gloves (Group 10, Index 1)
  {
    slot: 5,
    hex: '',
    group: 10,
    index: 1,
    id: 321,
    name: 'Dragon Gloves',
    level: 15,
    skill: false,
    luck: true,
    option: 7,
    durability: 255,
    serial: 12345683,
    excellentFlags: 0x0C,
    ancientOption: 0,
    option380: false,
    harmonyType: 3,
    harmonyLevel: 10,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 2,
    height: 2,
    isExcellent: true,
    isAncient: false,
    category: 'armor' as const,
    spriteKey: 'hand-front-right',
  },
  // Slot 6: Dragon Boots (Group 11, Index 1)
  {
    slot: 6,
    hex: '',
    group: 11,
    index: 1,
    id: 353,
    name: 'Dragon Boots',
    level: 15,
    skill: false,
    luck: true,
    option: 7,
    durability: 255,
    serial: 12345684,
    excellentFlags: 0x0C,
    ancientOption: 0,
    option380: false,
    harmonyType: 3,
    harmonyLevel: 10,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 2,
    height: 2,
    isExcellent: true,
    isAncient: false,
    category: 'armor' as const,
    spriteKey: 'shoe-formal',
  },
  // Slot 7: Wings of Dragon (Group 12, Index 5)
  {
    slot: 7,
    hex: '',
    group: 12,
    index: 5,
    id: 389,
    name: 'Wings of Dragon',
    level: 15,
    skill: false,
    luck: true,
    option: 7,
    durability: 255,
    serial: 12345685,
    excellentFlags: 0,
    ancientOption: 0,
    option380: false,
    harmonyType: 0,
    harmonyLevel: 0,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 2,
    height: 2,
    isExcellent: false,
    isAncient: false,
    category: 'wings' as const,
    spriteKey: 'butterfly',
  },
  // Slot 8: Horn of Fenrir (Group 13, Index 37)
  {
    slot: 8,
    hex: '',
    group: 13,
    index: 37,
    id: 453,
    name: 'Horn of Fenrir',
    level: 0,
    skill: false,
    luck: false,
    option: 0,
    durability: 255,
    serial: 12345686,
    excellentFlags: 0x01,
    ancientOption: 0,
    option380: false,
    harmonyType: 0,
    harmonyLevel: 0,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 1,
    height: 1,
    isExcellent: false,
    isAncient: false,
    category: 'pet' as const,
    spriteKey: 'paw',
  },
  // Slot 9: Pendant of Lightning (Group 13, Index 12)
  {
    slot: 9,
    hex: '',
    group: 13,
    index: 12,
    id: 428,
    name: 'Pendant of Lightning',
    level: 0,
    skill: false,
    luck: false,
    option: 7,
    durability: 255,
    serial: 12345687,
    excellentFlags: 0x22,
    ancientOption: 0,
    option380: false,
    harmonyType: 0,
    harmonyLevel: 0,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 1,
    height: 1,
    isExcellent: true,
    isAncient: false,
    category: 'jewelry' as const,
    spriteKey: 'necklace',
  },
  // Slot 10: Ring of Ice (Group 13, Index 8)
  {
    slot: 10,
    hex: '',
    group: 13,
    index: 8,
    id: 424,
    name: 'Ring of Ice',
    level: 0,
    skill: false,
    luck: false,
    option: 7,
    durability: 255,
    serial: 12345688,
    excellentFlags: 0x0C,
    ancientOption: 0,
    option380: false,
    harmonyType: 0,
    harmonyLevel: 0,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 1,
    height: 1,
    isExcellent: true,
    isAncient: false,
    category: 'jewelry' as const,
    spriteKey: 'ring',
  },
  // Slot 11: Ring of Poison (Group 13, Index 9)
  {
    slot: 11,
    hex: '',
    group: 13,
    index: 9,
    id: 425,
    name: 'Ring of Poison',
    level: 0,
    skill: false,
    luck: false,
    option: 7,
    durability: 255,
    serial: 12345689,
    excellentFlags: 0x0C,
    ancientOption: 0,
    option380: false,
    harmonyType: 0,
    harmonyLevel: 0,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 1,
    height: 1,
    isExcellent: true,
    isAncient: false,
    category: 'jewelry' as const,
    spriteKey: 'ring',
  },
  // Slot 12: Jewel of Bless (Group 14, Index 13)
  {
    slot: 12,
    hex: '',
    group: 14,
    index: 13,
    id: 461,
    name: 'Jewel of Bless',
    level: 0,
    skill: false,
    luck: false,
    option: 0,
    durability: 1,
    serial: 9001,
    excellentFlags: 0,
    ancientOption: 0,
    option380: false,
    harmonyType: 0,
    harmonyLevel: 0,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 1,
    height: 1,
    isExcellent: false,
    isAncient: false,
    category: 'consumable' as const,
    spriteKey: 'diamond',
  },
  // Slot 13: Jewel of Soul (Group 14, Index 14)
  {
    slot: 13,
    hex: '',
    group: 14,
    index: 14,
    id: 462,
    name: 'Jewel of Soul',
    level: 0,
    skill: false,
    luck: false,
    option: 0,
    durability: 1,
    serial: 9002,
    excellentFlags: 0,
    ancientOption: 0,
    option380: false,
    harmonyType: 0,
    harmonyLevel: 0,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 1,
    height: 1,
    isExcellent: false,
    isAncient: false,
    category: 'consumable' as const,
    spriteKey: 'diamond',
  },
  // Slot 14: Jewel of Chaos (Group 14, Index 15)
  {
    slot: 14,
    hex: '',
    group: 14,
    index: 15,
    id: 463,
    name: 'Jewel of Chaos',
    level: 0,
    skill: false,
    luck: false,
    option: 0,
    durability: 1,
    serial: 9003,
    excellentFlags: 0,
    ancientOption: 0,
    option380: false,
    harmonyType: 0,
    harmonyLevel: 0,
    sockets: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
    width: 1,
    height: 1,
    isExcellent: false,
    isAncient: false,
    category: 'consumable' as const,
    spriteKey: 'diamond',
  },
];

export const MOCK_INVENTORY_HEX = MuItemParser.rebuildInventoryHex(mockItems, 108);

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  Cuentas: 1248,
  Personajes: 3870,
  Online: 142,
  VIP: 384,
  hostIp: '127.0.0.1',
  connected: true,
  accountType: 'Premium',
};

export const MOCK_CHARACTERS: CharacterSummary[] = [
  { Name: 'TestBM', AccountID: 'test_admin', Class: 19, cLevel: 400, ResetCount: 1000, Money: 2000000000 },
  { Name: 'GrandWiz', AccountID: 'soul_master99', Class: 3, cLevel: 400, ResetCount: 950, Money: 1850000000 },
  { Name: 'ElfGoddess', AccountID: 'nature_queen', Class: 35, cLevel: 395, ResetCount: 650, Money: 940000000 },
  { Name: 'LordEmperor', AccountID: 'dark_ruler', Class: 66, cLevel: 400, ResetCount: 880, Money: 1999999999 },
  { Name: 'DuelKing', AccountID: 'gladiator_x', Class: 50, cLevel: 380, ResetCount: 420, Money: 600000000 },
  { Name: 'CurseMistress', AccountID: 'summoner_dark', Class: 83, cLevel: 400, ResetCount: 710, Money: 1200000000 },
  { Name: 'FistDestroyer', AccountID: 'rage_punch', Class: 98, cLevel: 350, ResetCount: 220, Money: 340000000 },
  { Name: 'NoviceKnight', AccountID: 'testuser1', Class: 16, cLevel: 150, ResetCount: 5, Money: 50000000 },
];

export const MOCK_CHARACTER_DETAILS: Record<string, CharacterDetail> = {
  'TestBM': {
    Name: 'TestBM',
    AccountID: 'test_admin',
    Class: 19, // Blade Master
    cLevel: 400,
    LevelUpPoint: 15000,
    MasterLevel: 250,
    MasterPoint: 25,
    Strength: 32767,
    Dexterity: 32767,
    Vitality: 32767,
    Energy: 32767,
    Leadership: 5000,
    Money: 2000000000,
    FruitPoint: 250,
    Inventory: MOCK_INVENTORY_HEX,
    MapNumber: 0, // Lorencia
    MapPosX: 125,
    MapPosY: 125,
    PkCount: 0,
    PkLevel: 3, // Commoner
    CtlCode: 32, // GameMaster
  },
  'GrandWiz': {
    Name: 'GrandWiz',
    AccountID: 'soul_master99',
    Class: 3, // Grand Master
    cLevel: 400,
    LevelUpPoint: 8000,
    MasterLevel: 210,
    MasterPoint: 12,
    Strength: 12000,
    Dexterity: 15000,
    Vitality: 18000,
    Energy: 32767,
    Leadership: 1000,
    Money: 1850000000,
    FruitPoint: 180,
    Inventory: MOCK_INVENTORY_HEX,
    MapNumber: 2, // Devias
    MapPosX: 210,
    MapPosY: 45,
    PkCount: 3,
    PkLevel: 4,
    CtlCode: 0,
  }
};

export const MOCK_RECENT_ACCOUNTS: AccountSummary[] = [
  { memb___id: 'test_admin', AccountLevel: 2, status: 'Active', regDate: '2026-01-15', online: true },
  { memb___id: 'soul_master99', AccountLevel: 2, status: 'Active', regDate: '2026-02-01', online: true },
  { memb___id: 'nature_queen', AccountLevel: 1, status: 'Active', regDate: '2026-02-14', online: false },
  { memb___id: 'dark_ruler', AccountLevel: 2, status: 'Active', regDate: '2026-02-20', online: true },
  { memb___id: 'gladiator_x', AccountLevel: 1, status: 'Active', regDate: '2026-03-01', online: false },
  { memb___id: 'novice_player', AccountLevel: 0, status: 'Active', regDate: '2026-03-05', online: false },
];
